Add Support for Java 8u171/172
antoineco/aco-oracle_java pull request #53
Opened 2018-04-18 09:08 UTC by mtron

2018-04-18 12:55 UTC, dalesit commented
Ah great, already been done. It's that time of year again... merge ASAP please, and update release on the forge...

2018-04-18 13:30 UTC, dalesit commented
"This JRE (version 8u172) will expire with the release of the next critical patch update scheduled for July 17, 2018" so make a note in your diaries... would be nice if we could get the next version released to the forge in advance of the expiry date...

2018-04-20 14:47 UTC, antoineco requested changes

2018-04-20 14:47 UTC, antoineco commented on manifests/init.pp
> +  if versioncmp($version_final, '8u172') >= 0 and $maj_version != '9' {
Will break all versions below 8u172, please revert.

2018-04-23 10:03 UTC, mtron commented
> Will break all versions below 8u172, please revert this particular change.

ups. sorry. Reverted

2018-04-23 10:36 UTC, mtron commented on manifests/init.pp
> +  if versioncmp($version_final, '8u172') >= 0 and $maj_version != '9' {
ups. sorry. Reverted

2018-04-23 11:23 UTC, antoineco approved these changes

2018-04-23 11:23 UTC, merged

2018-04-23 11:23 UTC, antoineco commented
Thanks @mtron! 🙌

2018-04-23 11:45 UTC, antoineco commented
Released in [v2.9.4](https://forge.puppet.com/aco/oracle_java/2.9.3/changelog)

2018-04-23 17:28 UTC, dalesit commented
Many thanks to you both👏